apiVersion: v1
kind: Service
metadata:
  name: tf-service
  labels:
    name: tf-service
    app: tf-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: tf-app-pod
    app: tf-app